services:

  # Servidor Web + PHP (front + api)
  app:
    build: .
    container_name: ${APP_NAME}_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  # Base de Datos MariaDB
  db:
    image: mariadb:10.5
    container_name: ${APP_NAME}_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: vitaminadedeficienciac.2026.com
      MARIADB_DATABASE: fitpower_db
      MARIADB_USER: usuario
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mariadb
      - ./api/config/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Interfaz gráfica para MariaDB
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data:
